# Generated by Django 6.0 on 2026-09-19 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo1', '0006_todo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushsubscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='karma',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_online',
        ),
        migrations.AddField(
            model_name='profile',
            name='text_box',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='text_box_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_completed', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streaks', to='todo1.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StreakCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField()),
                ('streak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='todo1.streak')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='PushSubscription',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
